- hosts: all
  become: true
  tasks:
     - name: delete deployment
       command: kubectl delete -f /home/ubuntu/deploy.yml
     - name: delete service
       command: kubectl delete -f /home/ubuntu/service.yml
     - name: delete k8 cluster
       shell: /home/ubuntu/./k8delete.sh
