kind: Deployment
apiVersion: apps/v1
metadata:
   name: sathavahana
spec:
   replicas: 3
   selector: 
    matchLabels:
     app: sathavahana
   template:
      metadata:
        labels:
          app: sathavahana
      spec:
       containers:
        - name: sathavahana
          image: sathadocker/webserver:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
