kind: Service                             
apiVersion: v1
metadata:
  name: sathavahana
  labels:
    app: sathavahana
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: sathavahana                   
  type: LoadBalancer
